# Generated by Django 5.0.6 on 2024-06-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISO_CODES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ISO Code',
                'verbose_name_plural': 'ISO Codes',
                'unique_together': {('iso_code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country_images/')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('Customer_website', models.URLField(blank=True, max_length=255, null=True)),
                ('costumer_fb_link', models.URLField(blank=True, max_length=255, null=True)),
                ('costumer_inst_link', models.URLField(blank=True, max_length=255, null=True)),
                ('costumer_x_link', models.URLField(blank=True, max_length=255, null=True)),
                ('costumer_linkedin_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry_days', models.PositiveIntegerField(default=30)),
                ('iso_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso', to='map.iso_codes')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iso_name', to='map.iso_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=True)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('business_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='map.country')),
                ('iso_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_iso_code', to='map.country')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='map.country')),
            ],
            options={
                'unique_together': {('location_name', 'latitude', 'longitude')},
            },
        ),
    ]
