# Generated by Django 5.0.6 on 2024-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='country_images/')),
                ('business_name', models.CharField(max_length=255)),
            ],
        ),
    ]
