# Generated by Django 5.0.6 on 2024-06-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iso_codes',
            options={'verbose_name': 'ISO Code', 'verbose_name_plural': 'ISO Codes'},
        ),
    ]
