# Generated by Django 5.0.6 on 2024-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso_codes',
            name='iso_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
