# Generated by Django 5.0.6 on 2024-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_iso_codes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Customer_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
