# Generated by Django 5.0.6 on 2024-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_country_customer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='costumer_fb_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='costumer_inst_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='costumer_x_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
