# Generated by Django 5.0.6 on 2024-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_country_costumer_fb_link_country_costumer_inst_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='costumer_linkedin_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
