# Generated by Django 5.0.6 on 2024-06-15 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_country_costumer_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='crated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
