# Generated by Django 5.0.6 on 2024-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_country_crated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='crated',
            new_name='created',
        ),
        migrations.AddField(
            model_name='country',
            name='expiry_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
