# Generated by Django 5.0.6 on 2024-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_rename_crated_country_created_country_expiry_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='expiry_days',
        ),
        migrations.AddField(
            model_name='country',
            name='expiry_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
