# Generated by Django 5.0.6 on 2024-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_country_expiry_days_country_expiry_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='expiry_minutes',
        ),
        migrations.AddField(
            model_name='country',
            name='expiry_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
